// "If that time doesn't work, when does?" — given a list of candidate
// appointment start times (typically generated by the caller around the
// proposed time) and an evaluator function, return the soonest feasible
// alternatives.
//
// Kept pure: the caller decides how to fetch journey timing for each
// candidate. Tests inject a synchronous evaluator.

import type { FeasibilityStatus } from "@/lib/types/domain";
import { addMinutes } from "@/lib/types/time";

export type Candidate = {
  appointmentStart: Date;
};

export type Evaluation = {
  status: FeasibilityStatus;
};

export type SuggestedAlternative<C extends Candidate> = {
  candidate: C;
  status: FeasibilityStatus;
};

const ACCEPTABLE: Readonly<FeasibilityStatus[]> = ["recommended", "tight"];

export function suggestAlternatives<C extends Candidate>(
  candidates: C[],
  evaluate: (c: C) => Evaluation,
  limit = 3,
): SuggestedAlternative<C>[] {
  const out: SuggestedAlternative<C>[] = [];
  for (const c of candidates) {
    if (out.length >= limit) break;
    const ev = evaluate(c);
    if (ACCEPTABLE.includes(ev.status)) {
      out.push({ candidate: c, status: ev.status });
    }
  }
  return out;
}

// Convenience: build a default candidate ladder around a proposed time —
// the same hour every 30 minutes for the next 6 hours, then the next two
// mornings at the same time. Callers can replace with a more sophisticated
// scheduler later.
export function defaultCandidateLadder(
  proposed: Date,
  options: { stepMinutes?: number; window?: number } = {},
): { appointmentStart: Date }[] {
  const step = options.stepMinutes ?? 30;
  const windowSteps = options.window ?? 12;
  const ladder: { appointmentStart: Date }[] = [];
  for (let i = 1; i <= windowSteps; i++) {
    ladder.push({ appointmentStart: addMinutes(proposed, step * i) });
  }
  // Two follow-up days at the same proposed clock time.
  for (let day = 1; day <= 2; day++) {
    const next = new Date(proposed);
    next.setDate(next.getDate() + day);
    ladder.push({ appointmentStart: next });
  }
  return ladder;
}
