// RailSmartr (a trading name of Assertis Ltd) eTicket parser.
//
// RailSmartr emails carry the journey in PDF + .pkpass attachments, not the body.
// The PDF is generated by TCPDF and, unlike Trainline's, extracts as ONE
// space-delimited run (no newlines), with everything inline-labelled — which
// makes it cleaner to parse than Trainline. A real outbound eTicket reads:
//
//   "AABTSKFL9ZB 18 Jun 2026 Out: WEL - HPD WELLINGBOROUGH WEL <arrow> HARPENDEN HPD
//    TICKET TYPE Anytime Day Return ROUTE ANY PERMITTED ADULT VALID UNTIL
//    26-30 Railcard 18 Jun 2026 Itinerary - Suggested 18 June:
//    07:25 East Midlands Railway From Wellingborough To Luton
//    08:13 Thameslink From Luton To Harpenden
//    Ticket Details: ... Ticket Number AABTSKFL9ZB Price £24.60 ... Order ID WEB000181489"
//
// Because Assertis white-labels ticketing for many retailers, this same layout
// is expected to generalise across the Assertis family — not just RailSmartr.

import type { ParsedTransportSegment } from "./types";
import { resolveStationName } from "./trainline-pdf";

const MONTHS: Record<string, string> = {
  jan: "01", feb: "02", mar: "03", apr: "04", may: "05", jun: "06",
  jul: "07", aug: "08", sep: "09", oct: "10", nov: "11", dec: "12",
};

function titleCase(s: string): string {
  return s
    .toLowerCase()
    .replace(/\b\w/g, (m) => m.toUpperCase())
    .trim();
}

// One leg of the suggested itinerary — RailSmartr gives departure time + operator
// + endpoints per leg (arrival times aren't printed; the solver fills them).
export type RailsmartrLeg = {
  departure_time: string;
  operator: string;
  from_name: string;
  to_name: string;
};

export type RailsmartrPdfTicket = {
  direction: "out" | "ret" | null;
  from_code: string;
  to_code: string;
  from_name: string;
  to_name: string;
  date: string; // YYYY-MM-DD
  ticket_type: string | null;
  route_restriction: string | null;
  railcard: string | null;
  price: number | null;
  ticket_number: string | null;
  order_id: string | null;
  barcode_data: string | null; // filled from the Aztec image by the caller
  legs: RailsmartrLeg[];
};

export function parseRailsmartrPdfText(pdfText: string): RailsmartrPdfTicket | null {
  // Normalise to a single space-delimited run — robust whether unpdf merged with
  // spaces or newlines.
  const text = pdfText.replace(/\s+/g, " ").trim();

  // Direction + fare endpoints: "Out: WEL - HPD" / "Ret: HPD - WEL".
  const dir = text.match(/\b(Out|Ret)(?:urn|bound)?\s*:\s*([A-Z]{3})\s*[-–]\s*([A-Z]{3})\b/);
  const direction = dir ? (dir[1].toLowerCase() === "out" ? "out" : "ret") : null;
  const fromCode = dir?.[2] ?? "";
  const toCode = dir?.[3] ?? "";

  // Date — "18 Jun 2026".
  let date = "";
  const dm = text.match(/(\d{1,2})\s+([A-Za-z]{3,})\s+(\d{4})/);
  if (dm) {
    const day = dm[1].padStart(2, "0");
    const month = MONTHS[dm[2].slice(0, 3).toLowerCase()] ?? "01";
    date = `${dm[3]}-${month}-${day}`;
  }

  // Ticket type + route restriction: "TICKET TYPE <type> ROUTE <route> ADULT".
  const tr = text.match(/TICKET TYPE\s+(.+?)\s+ROUTE\s+(.+?)\s+(?:ADULT|CHILD|SENIOR|YOUTH|\d)/i);
  const ticketType = tr ? tr[1].trim() : null;
  const routeRestriction = tr ? tr[2].trim() : null;

  // Railcard — "26-30 Railcard", "Two Together Railcard", etc.
  const rc = text.match(
    /\b(\d{2}-\d{2}|16-17|16-25|26-30|Senior|Disabled|Family\s*&\s*Friends|Two\s*Together|Network|Veterans)\s+Railcard/i,
  );
  const railcard = rc ? rc[1].trim() : null;

  // Price — "Price £24.60" (the encoding may render "Â£").
  const pm = text.match(/Price\s+(?:Â£|£|GBP\s*)?([\d,]+\.\d{2})/i);
  const price = pm ? parseFloat(pm[1].replace(/,/g, "")) : null;

  // Ticket number — labelled, or the bold ref at the very start of the PDF.
  const tn =
    text.match(/Ticket Number\s+([A-Z0-9]{6,})/i) ?? text.match(/^([A-Z0-9]{8,})\b/);
  const ticketNumber = tn?.[1] ?? null;

  // Order ID — "Order ID WEB000181489".
  const oid = text.match(/Order ID\s+([A-Z0-9]+)/i);
  const orderId = oid?.[1] ?? null;

  // Suggested itinerary legs: "HH:MM <operator> From <X> To <Y>", one per leg.
  const legs: RailsmartrLeg[] = [];
  const legRe =
    /(\d{1,2}:\d{2})\s+(.+?)\s+From\s+(.+?)\s+To\s+(.+?)(?=\s+\d{1,2}:\d{2}\s+|\s+Ticket Details|\s*$)/gi;
  let lm: RegExpExecArray | null;
  while ((lm = legRe.exec(text)) !== null) {
    legs.push({
      departure_time: lm[1],
      operator: lm[2].trim(),
      from_name: titleCase(lm[3]),
      to_name: titleCase(lm[4]),
    });
  }

  // Need at least the fare endpoints or a leg to be a real ticket.
  if (!fromCode && !toCode && legs.length === 0) return null;

  const fromName = legs[0]?.from_name || resolveStationName(fromCode) || titleCase(fromCode);
  const toName =
    legs[legs.length - 1]?.to_name || resolveStationName(toCode) || titleCase(toCode);

  return {
    direction,
    from_code: fromCode,
    to_code: toCode,
    from_name: fromName,
    to_name: toName,
    date,
    ticket_type: ticketType,
    route_restriction: routeRestriction,
    railcard,
    price,
    ticket_number: ticketNumber,
    order_id: orderId,
    barcode_data: null,
    legs,
  };
}

// Flatten parsed tickets into timeline segments. Each itinerary leg becomes a
// segment (so a change-of-train — e.g. at Luton — is modelled as adjacent
// segments). The ticket-level facts (type, route, ref, Aztec) attach to the FIRST
// leg of each ticket — that's the leg the passenger boards with that eTicket.
export function railsmartrTicketsToSegments(
  tickets: RailsmartrPdfTicket[],
  fallbackDate: string,
): ParsedTransportSegment[] {
  const segments: ParsedTransportSegment[] = [];
  for (const t of tickets) {
    const legs =
      t.legs.length > 0
        ? t.legs
        : [{ departure_time: "", operator: "", from_name: t.from_name, to_name: t.to_name }];
    legs.forEach((leg, i) => {
      const first = i === 0;
      const last = i === legs.length - 1;
      segments.push({
        from_station: leg.from_name,
        to_station: leg.to_name,
        from_station_code: first ? t.from_code || null : null,
        to_station_code: last ? t.to_code || null : null,
        departure_date: t.date || fallbackDate,
        departure_time: leg.departure_time || "00:00",
        arrival_date: t.date || fallbackDate,
        arrival_time: "",
        service_number: null,
        operator: leg.operator || null,
        route_restriction: first ? t.route_restriction : null,
        ticket_type: first ? t.ticket_type : null,
        platform_dep: null,
        platform_arr: null,
        coach: null,
        seat: null,
        barcode_ref: first ? t.ticket_number : null,
        barcode_data: first ? t.barcode_data : null,
      });
    });
  }
  return segments;
}
